name: README Stars
on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2626651
          leaderboardId: 2626651
          sessionCookie: ${{ secrets.AOC_SESSION }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update README stars
