name: README Stars
on:
  schedule:
    - cron: "51 */4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: k2bd/advent-readme-stars@v1
        with:
          userId: 2626651
          leaderboardId: 2626651
          sessionCookie: ${{ secrets.AOC_SESSION }}
